#!/bin/python3

import math
import os
import random
import re
import sys
import bisect

# Complete the activityNotifications function below.
def activityNotifications(expenditure, d):
    median, n = 0, 0
    median_list = []
    for index, item in enumerate(expenditure):
        if index >= d:
            if d%2 != 0:
                median = median_list[d//2]
            else:
                median = (median_list[d//2-1] + median_list[d//2])/2.0
            if item >= 2 * median:
                n += 1
            del median_list[bisect.bisect_left(median_list, expenditure[index-d])]
        bisect.insort_left(median_list, item)
    return n



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nd = input().split()

    n = int(nd[0])

    d = int(nd[1])

    expenditure = list(map(int, input().rstrip().split()))

    result = activityNotifications(expenditure, d)

    fptr.write(str(result) + '\n')

    fptr.close()
